stages:
  - build

variables:
  REGISTRY: hub.alterway.fr

before_script:
  - if [[ "$CI_BUILD_REF_NAME" != master ]]; then REGISTRY="$REGISTRY/$CI_BUILD_REF_NAME"; fi

build:
  stage: build
  script:
    - docker build --pull -t $REGISTRY/httpd:2.4 2.4/
    - docker push $REGISTRY/httpd:2.4
  only:
    - preprod
    - master
